kind: ConfigMap
apiVersion: v1
metadata:
  name: dns-default
  namespace: openshift-dns
  labels:
    dns.operator.openshift.io/owning-dns: default
data:
  Corefile: |
    .:5353 {
        rewrite stop type AAAA A
        bufsize 512
        errors
        log . {
            class error
        }
        health {
            lameduck 20s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus 127.0.0.1:9153
        forward . /etc/resolv.conf {
            policy sequential
        }
        cache 900 {
            denial 9984 30
        }
        reload
    }
